# ./tasks/install_runit.yml

# install runit

- name: runit | Installing runit repo rmp
  shell: "curl -s https://packagecloud.io/install/repositories/imeyer/runit/script.rpm.sh | sudo bash"

- name: runit | Installing runit
  yum:
    name: runit
    state: present
    update_cache: yes



